import path from "path";

/**
 * Product files must live on a Railway Volume in production. The application
 * bundle (including `public/`) is replaced on deploy and is not durable.
 */
export function getUploadsDirectory() {
  const configuredDirectory = process.env.UPLOADS_DIR;

  if (configuredDirectory) return path.resolve(configuredDirectory);

  if (process.env.NODE_ENV === "production") {
    throw new Error("UPLOADS_DIR is not configured. Set it to a mounted persistent volume path, for example /app/data/uploads.");
  }

  // Local development remains convenient, but this fallback is deliberately
  // unavailable in production.
  return path.join(process.cwd(), "public", "uploads");
}

export function getUploadPath(filename: string) {
  // Uploaded filenames are generated by this application. This additional
  // check ensures the public read route can never escape the upload directory.
  if (!/^[a-f0-9-]{36}\.(jpg|png|webp)$/.test(filename)) return null;
  return path.join(getUploadsDirectory(), filename);
}

export function getUploadContentType(filename: string) {
  if (filename.endsWith(".jpg")) return "image/jpeg";
  if (filename.endsWith(".png")) return "image/png";
  if (filename.endsWith(".webp")) return "image/webp";
  return null;
}
